### ISSUE TITLE
“Widely available” date isn’t useful for old features

### ISSUE THREAD

**Issue by simevidas** [web-platform-dx/web-features-explorer#19]
Example: `<button>`

https://web-platform-dx.github.io/web-features-explorer/features/button/

It says “Widely available since 2018-01-29”. The reason for such a late date is “Edge 12 Released on 2015-07-29” (30 months before).

That 2018 date isn’t useful, and it might even confuse some developers and make them think that `<button>` is a newer feature than it is. `<button>` has been widely available for a very long time, and the launch of Edge in 2015 doesn’t change anything about that. 

Maybe “widely available” should only include a date in cases when a modern browser **didn’t support a feature at some point**. In all other cases, it could just say ”Widely available for a long time”.

In the case of `<button>`, all the browser versions listed on the page are the initial versions of these browsers. In other words, all the listed browsers supported `<button>` from the beginning. Therefore, `<button>` has been ”widely available for a long time”.

**Comment by captainbrosset** [comment]
Thanks @simevidas. I agree that the date doesn't help here, and can sometimes be confusing.
I'll remove it for now. We can figure out later if adding it in certain cases is useful.
