### ISSUE TITLE
Better default sorting

### ISSUE THREAD

**Issue by kizu** [web-platform-dx/web-features-explorer#40]
I really like how on the “[Newly available](https://web-platform-dx.github.io/web-features-explorer/newly-available/)” tab the features are sorted by date.

It would be great to also do the same for the other tabs:

- [Widely Available](https://web-platform-dx.github.io/web-features-explorer/widely-available/) — could be ordered by the time it became such, so the “newer” widely available features would be on top (and it would be great to display the date as well).
- [One Missing Engine](https://web-platform-dx.github.io/web-features-explorer/one-missing-engine/) — could use the “availability blocked”, and show the most recently updated entries as well.
- [Limited Availability](https://web-platform-dx.github.io/web-features-explorer/limited-availability/) — less useful to have this, but maybe could be sorted by the latest update to the feature support?

**Comment by captainbrosset** [comment]
> [Widely Available](https://web-platform-dx.github.io/web-features-explorer/widely-available/) — could be ordered by the time it became such, so the “newer” widely available features would be on top (and it would be great to display the date as well).

This view is already ordered by date, from most to least recent. We used to display the date, but removed it for some reason I can't remember. I think I'll add it back.

> [One Missing Engine](https://web-platform-dx.github.io/web-features-explorer/one-missing-engine/) — could use the “availability blocked”, and show the most recently updated entries as well.

I'll try something.

> [Limited Availability](https://web-platform-dx.github.io/web-features-explorer/limited-availability/) — less useful to have this, but maybe could be sorted by the latest update to the feature support?

That's a great idea, this way you can see which features are getting worked on.

**Comment by captainbrosset** [comment]
@kizu please take a look and let me know if you like the changes.

- One missing engine: https://web-platform-dx.github.io/web-features-explorer/one-missing-engine/
- One missing engine (oldest first): https://web-platform-dx.github.io/web-features-explorer/one-missing-engine-oldest/
- Limited availability, latest updated feature first (irrespective of browser): https://web-platform-dx.github.io/web-features-explorer/limited-availability/
- Newly available, most recent baseline feature first: https://web-platform-dx.github.io/web-features-explorer/newly-available/

**Comment by kizu** [comment]
This is great! Very useful, and I love that the browser names now have the release date for them. Thanks for doing this so quickly!
